---
# tasks file for wblotevogel.redis

  - name: update apt
    apt:
      update_cache: yes
      cache_valid_time: 1800


  - name: ensure redis is installed
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - redis-server

  - name: configure redis
    template:
      src: templates/redis.conf.j2
      dest: /etc/redis/redis.conf
      owner: redis
      group: redis
      mode: 0640
    notify: redis restart

